### ISSUE TITLE
Testiranje

### ISSUE THREAD

**Issue by nyanSpruk** [nyanSpruk/PRPO-Naloge#11]
Vašo aplikacijo lahko izvajate:

- [x] Aplikacijo prevedete z ukazom mvn clean package in dobljen jar poženete z java -jar .\target\simple-jdbc-sample-1.0.0-SNAPSHOT.jar.

- [x]  Če je šlo vse po načrtu bi morala vaša aplikacija biti dostopna na naslovu localhost:8080/imeServleta.

**Comment by nyanSpruk** [comment]
Completed at #13

**Comment by bl4ko** [comment]
Tests fail, because server is not active during the maven test phase.

**Comment by bl4ko** [comment]
Possible solution could be in changing `ci.yaml`:
```yml
name: Build and test

on: 
  push: 
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    strategy:
      matrix: 
        os: [ubuntu-latest]
        version: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'
      - name: Build project with Maven
        run: mvn -f hello-world/pom.xml install -DskipTests
      - name: Run server
        run: java -jar ./hello-world/target/hello-world-1.0-SNAPSHOT.jar
      - name: Run tests
        run: mvn surefire:test

```
