### ISSUE TITLE
Update Git Actions on every push

### ISSUE THREAD

**Issue by nyanSpruk** [nyanSpruk/PRPO-Naloge#17]
Currently it only runs to 
```yaml
on
    push:
        branches: ["feature/*"]
```
We want it on every branch

**Comment by bl4ko** [comment]
I think this one would be even better:

```yaml
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      -  ...
```

This also adds the [functionality](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) of ignoring certain changes. For example when we change certain files in paths that have no effect on our project, this action is not run.
